import type { Phone } from './types';

export type Currency = 'USD' | 'EUR' | 'RUB' | 'KZT';
export type Lang = 'ru' | 'en';

export const CURRENCIES: Record<Currency, number> = {
  USD: 1 / 460,
  EUR: 1 / 500,
  RUB: 1 / 5,
  KZT: 1,
};

const _DICT: Record<string, Record<Lang, string>> = {
  brand:        { ru: 'PhoneMarket',            en: 'PhoneMarket' },
  home:         { ru: 'Главная',                en: 'Home' },
  catalog:      { ru: 'Каталог',                en: 'Catalog' },
  cart:         { ru: 'Корзина',                en: 'Cart' },
  about:        { ru: 'О нас',                  en: 'About' },
  myAccount:    { ru: 'Мой аккаунт',            en: 'My Account' },
  signIn:       { ru: 'Войти',                  en: 'Sign In' },
  signUp:       { ru: 'Регистрация',            en: 'Sign Up' },
  search:       { ru: 'Поиск...',               en: 'Search...' },
  priceFrom:    { ru: 'Цена от',                en: 'Price from' },
  priceTo:      { ru: 'Цена до',                en: 'Price to' },
  all:          { ru: 'Все',                    en: 'All' },
  storage:      { ru: 'Память',                 en: 'Storage' },
  addToCart:    { ru: 'В корзину',              en: 'Add to Cart' },
  addToCart2:   { ru: 'Добавить в корзину',     en: 'Add to Cart' },
  heroTitle:    { ru: 'Лучшие смартфоны по лучшим ценам', en: 'Best phones at best prices' },
  heroSub:      { ru: 'Огромный выбор оригинальных смартфонов с гарантией и быстрой доставкой по всему Казахстану', en: 'Huge selection of original smartphones with warranty and fast delivery across Kazakhstan' },
  heroBtn:      { ru: 'Смотреть каталог',       en: 'View Catalog' },
  whyTitle:     { ru: 'Почему выбирают нас',   en: 'Why choose us' },
  why1:         { ru: 'Оригинальная продукция', en: 'Original Products' },
  why1desc:     { ru: 'Только сертифицированные устройства с официальной гарантией', en: 'Only certified devices with official warranty' },
  why2:         { ru: 'Быстрая доставка',       en: 'Fast Delivery' },
  why2desc:     { ru: 'Доставка по всему Казахстану за 1-3 дня', en: 'Delivery across Kazakhstan in 1-3 days' },
  why3:         { ru: 'Лучшие цены',            en: 'Best Prices' },
  why3desc:     { ru: 'Гарантируем низкие цены и регулярные акции', en: 'Best prices guaranteed with regular promotions' },
  why4:         { ru: 'Поддержка 24/7',         en: '24/7 Support' },
  why4desc:     { ru: 'Консультация и помощь в любое время', en: 'Consultation and help anytime' },
  newTitle:     { ru: 'Новинки',                en: 'New Arrivals' },
  new1:         { ru: 'iPhone 16 Pro Max',      en: 'iPhone 16 Pro Max' },
  new1desc:     { ru: 'Флагман Apple с чипом A18 Pro и профессиональной камерой', en: 'Apple flagship with A18 Pro chip and pro-grade camera' },
  new2:         { ru: 'Galaxy S25 Ultra',       en: 'Galaxy S25 Ultra' },
  new2desc:     { ru: 'Ультимативный Galaxy с S Pen и 200MP камерой', en: 'Ultimate Galaxy with S Pen and 200MP camera' },
  new3:         { ru: 'Google Pixel 9 Pro',     en: 'Google Pixel 9 Pro' },
  new3desc:     { ru: 'ИИ-флагман Google с Tensor G4 и 50MP камерой', en: 'Google AI flagship with Tensor G4 and 50MP camera' },
  newBtn:       { ru: 'Подробнее',              en: 'Learn More' },
  brandsTitle:  { ru: 'Бренды',                 en: 'Brands' },
  bannerTitle:  { ru: 'Специальное предложение', en: 'Special Offer' },
  bannerText:   { ru: 'Скидки до 30% на избранные модели. Успей купить!', en: 'Up to 30% off selected models. Shop now!' },
  bannerBtn:    { ru: 'Перейти к покупкам',     en: 'Start Shopping' },
  banner2Title: { ru: 'iPhone 16 Pro Max',     en: 'iPhone 16 Pro Max' },
  banner2Text:  { ru: 'Флагманский A18 Pro чип. Титан. Профессиональная камера. От 649 000 ₸', en: 'A18 Pro chip. Titanium. Pro camera system. From 649,000 KZT' },
  banner2Btn:   { ru: 'Узнать больше',          en: 'Learn More' },
  banner3Title: { ru: 'Samsung Galaxy S25 Ultra', en: 'Samsung Galaxy S25 Ultra' },
  banner3Text:  { ru: '200MP камера. S Pen. Snapdragon 8 Elite. Искусственный интеллект Galaxy AI.', en: '200MP camera. S Pen. Snapdragon 8 Elite. Galaxy AI.' },
  banner3Btn:   { ru: 'Смотреть',               en: 'View' },
  banner4Title: { ru: 'Аксессуары в подарок',   en: 'Free Accessories' },
  banner4Text:  { ru: 'При покупке любого смартфона — защитное стекло и чехол в подарок!', en: 'Free screen protector and case with any phone purchase!' },
  banner4Btn:   { ru: 'Выбрать смартфон',        en: 'Choose Phone' },
  popular:      { ru: 'Популярные модели',       en: 'Popular Models' },
  allCatalog:   { ru: 'Весь каталог',           en: 'All Catalog' },
  recent:       { ru: 'Недавно просмотренные',   en: 'Recently Viewed' },
  back:         { ru: 'Назад',                  en: 'Back' },
  details:      { ru: 'Характеристики',          en: 'Details' },
  aboutTitle:   { ru: 'О PhoneMarket',          en: 'About PhoneMarket' },
  aboutDesc:    { ru: 'PhoneMarket — ведущий магазин смартфонов в Казахстане. Мы предлагаем широкий ассортимент оригинальных устройств от мировых брендов по конкурентоспособным ценам.', en: 'PhoneMarket is the leading smartphone store in Kazakhstan. We offer a wide range of original devices from global brands at competitive prices.' },
  aboutMissionDesc: { ru: 'Наша миссия — сделать современные технологии доступными каждому. Мы тщательно отбираем каждое устройство и предоставляем официальную гарантию.', en: 'Our mission is to make modern technology accessible to everyone. We carefully select every device and provide an official warranty.' },
  aboutTeam:    { ru: 'Наша команда',           en: 'Our Team' },
  aboutContact: { ru: 'Контакты',               en: 'Contact Us' },
  aboutAddress: { ru: 'г. Алматы, ул. Абая 100', en: 'Almaty, Abay St. 100' },
  aboutPhone:   { ru: '+7 (777) 123-45-67',     en: '+7 (777) 123-45-67' },
  aboutEmail:   { ru: 'info@phonemarket.kz',    en: 'info@phonemarket.kz' },
  loginRequired:{ ru: 'Войдите в аккаунт',       en: 'Login required' },
  orderHistory: { ru: 'История заказов',        en: 'Order History' },
  noOrders:     { ru: 'У вас пока нет заказов',  en: 'No orders yet' },
  total:        { ru: 'Итого',                  en: 'Total' },
  cartEmpty:    { ru: 'Корзина пуста',          en: 'Cart is empty' },
  goCatalog:    { ru: 'Перейти в каталог',      en: 'Go to Catalog' },
  subtotal:     { ru: 'Подытог',                en: 'Subtotal' },
  delivery:     { ru: 'Доставка',               en: 'Delivery' },
  free:         { ru: 'Бесплатно',              en: 'Free' },
  checkout:     { ru: 'Оформить заказ',          en: 'Checkout' },
  clearCart:    { ru: 'Очистить корзину',       en: 'Clear Cart' },
  loginSuccess: { ru: 'Успешный вход',          en: 'Login successful' },
  loginError:   { ru: 'Неверный email или пароль', en: 'Invalid email or password' },
  registerSuccess: { ru: 'Регистрация успешна', en: 'Registration successful' },
  registerError:{ ru: 'Ошибка регистрации',     en: 'Registration error' },
  loginBtn:     { ru: 'Войти',                  en: 'Log In' },
  registerBtn:  { ru: 'Зарегистрироваться',     en: 'Register' },
  email:        { ru: 'Email',                  en: 'Email' },
  password:     { ru: 'Пароль',                 en: 'Password' },
  name:         { ru: 'Имя',                    en: 'Name' },
  confirmPass:  { ru: 'Подтвердите пароль',     en: 'Confirm Password' },
  noAccount:    { ru: 'Нет аккаунта?',          en: 'No account?' },
  haveAccount:  { ru: 'Уже есть аккаунт?',      en: 'Already have an account?' },
};

export function t(key: string, lang: Lang): string {
  return _DICT[key]?.[lang] ?? key;
}

export function fmtPrice(kzt: number, currency: Currency = 'USD'): string {
  const rate = CURRENCIES[currency] ?? 1;
  const value = kzt * rate;
  return value.toLocaleString('ru-RU', {
    style: 'currency',
    currency,
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  });
}

export const BRANDS: string[] = ['apple', 'samsung', 'xiaomi', 'google', 'oneplus', 'nothing', 'oppo', 'honor', 'realme'];

export const PHONES: Phone[] = [
  { id: 1, brand: 'apple', name: 'iPhone 16 Pro Max', price: 649000, storage: '512GB', img: 'https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-16-pro-max.jpg',
    desc: 'The ultimate iPhone with A18 Pro chip, 6.9" OLED display, and pro-grade camera system.',
    specs: [{ label: 'Display', value: '6.9" OLED 2868x1320' }, { label: 'Chip', value: 'A18 Pro' }, { label: 'Camera', value: '48+48+12 MP' }, { label: 'Battery', value: '4685 mAh' }] },
  { id: 2, brand: 'apple', name: 'iPhone 16 Pro', price: 549000, storage: '256GB', img: 'https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-16-pro.jpg',
    desc: 'Powerful A18 Pro processor, 6.3" OLED, and advanced triple camera in a compact pro body.',
    specs: [{ label: 'Display', value: '6.3" OLED 2622x1206' }, { label: 'Chip', value: 'A18 Pro' }, { label: 'Camera', value: '48+48+12 MP' }, { label: 'Battery', value: '3582 mAh' }] },
  { id: 3, brand: 'apple', name: 'iPhone 16', price: 499000, storage: '128GB', img: 'https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-16.jpg',
    desc: 'The latest iPhone with A18 chip, 6.1" OLED, and a dual-camera system with spatial video.',
    specs: [{ label: 'Display', value: '6.1" OLED 2556x1179' }, { label: 'Chip', value: 'A18' }, { label: 'Camera', value: '48+12 MP' }, { label: 'Battery', value: '3561 mAh' }] },
  { id: 4, brand: 'apple', name: 'iPhone 16 Plus', price: 539000, storage: '128GB', img: 'https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-16-plus.jpg',
    desc: 'Big-screen iPhone with 6.7" OLED, A18 chip, and excellent battery life.',
    specs: [{ label: 'Display', value: '6.7" OLED 2796x1290' }, { label: 'Chip', value: 'A18' }, { label: 'Camera', value: '48+12 MP' }, { label: 'Battery', value: '4674 mAh' }] },
  { id: 5, brand: 'apple', name: 'iPhone 15 Pro Max', price: 579000, storage: '512GB', img: 'https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-15-pro-max.jpg',
    desc: 'Flagship iPhone with A17 Pro chip, titanium design, and 5x optical zoom.',
    specs: [{ label: 'Display', value: '6.7" OLED 2796x1290' }, { label: 'Chip', value: 'A17 Pro' }, { label: 'Camera', value: '48+12+12 MP' }, { label: 'Battery', value: '4422 mAh' }] },
  { id: 6, brand: 'apple', name: 'iPhone 15 Pro', price: 429000, storage: '256GB', img: 'https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-15-pro.jpg',
    desc: 'Pro power in a compact form with A17 Pro, titanium frame, and 48MP main camera.',
    specs: [{ label: 'Display', value: '6.1" OLED 2556x1179' }, { label: 'Chip', value: 'A17 Pro' }, { label: 'Camera', value: '48+12+12 MP' }, { label: 'Battery', value: '3274 mAh' }] },
  { id: 7, brand: 'samsung', name: 'Samsung Galaxy S25 Ultra', price: 579000, storage: '512GB', img: 'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s25-ultra-sm-s938.jpg',
    desc: 'The ultimate Galaxy with Snapdragon 8 Elite, S Pen, 200MP camera, and a stunning 6.9" display.',
    specs: [{ label: 'Display', value: '6.9" Dynamic AMOLED 3120x1440' }, { label: 'Chip', value: 'Snapdragon 8 Elite' }, { label: 'Camera', value: '200+50+50+10 MP' }, { label: 'Battery', value: '5000 mAh' }] },
  { id: 8, brand: 'samsung', name: 'Samsung Galaxy S25+', price: 479000, storage: '256GB', img: 'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s25-plus-sm-s936.jpg',
    desc: 'Large-screen flagship with Snapdragon 8 Elite, 50MP camera, and 4900 mAh battery.',
    specs: [{ label: 'Display', value: '6.7" Dynamic AMOLED 3120x1440' }, { label: 'Chip', value: 'Snapdragon 8 Elite' }, { label: 'Camera', value: '50+10+12 MP' }, { label: 'Battery', value: '4900 mAh' }] },
  { id: 9, brand: 'samsung', name: 'Samsung Galaxy S25', price: 429000, storage: '256GB', img: 'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s25-sm-s931.jpg',
    desc: 'Compact flagship with Snapdragon 8 Elite, 50MP camera, and Galaxy AI features.',
    specs: [{ label: 'Display', value: '6.2" Dynamic AMOLED 2340x1080' }, { label: 'Chip', value: 'Snapdragon 8 Elite' }, { label: 'Camera', value: '50+10+12 MP' }, { label: 'Battery', value: '4000 mAh' }] },
  { id: 10, brand: 'samsung', name: 'Samsung Galaxy S24', price: 399000, storage: '256GB', img: 'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s24-5g-sm-s921.jpg',
    desc: 'Premium Galaxy with Exynos 2400, 50MP camera, and Galaxy AI intelligence.',
    specs: [{ label: 'Display', value: '6.2" Dynamic AMOLED 2340x1080' }, { label: 'Chip', value: 'Exynos 2400' }, { label: 'Camera', value: '50+10+12 MP' }, { label: 'Battery', value: '4000 mAh' }] },
  { id: 11, brand: 'samsung', name: 'Samsung Galaxy Z Fold6', price: 789000, storage: '512GB', img: 'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-z-fold6.jpg',
    desc: 'Foldable marvel with 7.6" inner display, multitasking power, and premium design.',
    specs: [{ label: 'Display', value: '7.6" Foldable AMOLED 2160x1856' }, { label: 'Chip', value: 'Snapdragon 8 Gen 3' }, { label: 'Camera', value: '50+12+10 MP' }, { label: 'Battery', value: '4400 mAh' }] },
  { id: 12, brand: 'samsung', name: 'Samsung Galaxy A55', price: 219000, storage: '128GB', img: 'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a55.jpg',
    desc: 'Mid-range star with Super AMOLED 120Hz display, 50MP OIS camera, and IP67 rating.',
    specs: [{ label: 'Display', value: '6.6" Super AMOLED 2340x1080 120Hz' }, { label: 'Chip', value: 'Exynos 1480' }, { label: 'Camera', value: '50+12+5 MP' }, { label: 'Battery', value: '5000 mAh' }] },
  { id: 13, brand: 'samsung', name: 'Samsung Galaxy A35', price: 179000, storage: '128GB', img: 'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a35.jpg',
    desc: 'Affordable Galaxy with 6.6" Super AMOLED, 50MP camera, and 5000 mAh battery.',
    specs: [{ label: 'Display', value: '6.6" Super AMOLED 2340x1080 120Hz' }, { label: 'Chip', value: 'Exynos 1380' }, { label: 'Camera', value: '50+8+5 MP' }, { label: 'Battery', value: '5000 mAh' }] },
  { id: 14, brand: 'xiaomi', name: 'Xiaomi 14 Pro', price: 349000, storage: '512GB', img: 'https://fdn2.gsmarena.com/vv/bigpic/xiaomi-14-pro.jpg',
    desc: 'Leica-powered flagship with Snapdragon 8 Gen 3, 50MP triple camera, and 120W charging.',
    specs: [{ label: 'Display', value: '6.73" LTPO AMOLED 3200x1440 120Hz' }, { label: 'Chip', value: 'Snapdragon 8 Gen 3' }, { label: 'Camera', value: '50+50+50 MP Leica' }, { label: 'Battery', value: '4880 mAh 120W' }] },
  { id: 15, brand: 'xiaomi', name: 'Xiaomi 14', price: 299000, storage: '256GB', img: 'https://fdn2.gsmarena.com/vv/bigpic/xiaomi-14.jpg',
    desc: 'Compact Leica flagship with Snapdragon 8 Gen 3 and 50MP triple camera.',
    specs: [{ label: 'Display', value: '6.36" LTPO AMOLED 2670x1200 120Hz' }, { label: 'Chip', value: 'Snapdragon 8 Gen 3' }, { label: 'Camera', value: '50+50+50 MP Leica' }, { label: 'Battery', value: '4610 mAh 90W' }] },
  { id: 16, brand: 'xiaomi', name: 'Xiaomi Redmi Note 13 Pro', price: 189000, storage: '256GB', img: 'https://fdn2.gsmarena.com/vv/bigpic/xiaomi-redmi-note-13-pro-5g.jpg',
    desc: 'Best-selling mid-ranger with 200MP camera, 120Hz AMOLED, and 67W turbo charging.',
    specs: [{ label: 'Display', value: '6.67" AMOLED 2712x1220 120Hz' }, { label: 'Chip', value: 'Snapdragon 7s Gen 2' }, { label: 'Camera', value: '200+8+2 MP' }, { label: 'Battery', value: '5100 mAh 67W' }] },
  { id: 17, brand: 'google', name: 'Google Pixel 9 Pro', price: 429000, storage: '256GB', img: 'https://fdn2.gsmarena.com/vv/bigpic/google-pixel-9-pro-.jpg',
    desc: 'Google\'s AI-powered flagship with Tensor G4, 50MP camera, and 7 years of updates.',
    specs: [{ label: 'Display', value: '6.3" LTPO OLED 2856x1280 120Hz' }, { label: 'Chip', value: 'Tensor G4' }, { label: 'Camera', value: '50+48+48 MP' }, { label: 'Battery', value: '4700 mAh' }] },
  { id: 18, brand: 'oneplus', name: 'OnePlus 13', price: 389000, storage: '256GB', img: 'https://fdn2.gsmarena.com/vv/bigpic/oneplus-13.jpg',
    desc: 'Fast and smooth flagship with Snapdragon 8 Elite, 50MP Hasselblad camera, and 100W charging.',
    specs: [{ label: 'Display', value: '6.82" LTPO AMOLED 3168x1440 120Hz' }, { label: 'Chip', value: 'Snapdragon 8 Elite' }, { label: 'Camera', value: '50+50+50 MP Hasselblad' }, { label: 'Battery', value: '6000 mAh 100W' }] },
  { id: 19, brand: 'nothing', name: 'Nothing Phone (3)', price: 319000, storage: '256GB', img: 'https://fdn2.gsmarena.com/vv/bigpic/nothing-phone-3.jpg',
    desc: 'Iconic transparent design with Glyph interface, Snapdragon 8s Gen 3, and 50MP dual camera.',
    specs: [{ label: 'Display', value: '6.7" LTPO AMOLED 2412x1084 120Hz' }, { label: 'Chip', value: 'Snapdragon 8s Gen 3' }, { label: 'Camera', value: '50+50 MP' }, { label: 'Battery', value: '5000 mAh 45W' }] },
  { id: 20, brand: 'oppo', name: 'Oppo Find X8', price: 359000, storage: '256GB', img: 'https://fdn2.gsmarena.com/vv/bigpic/oppo-find-x8.jpg',
    desc: 'Slim flagship with MediaTek Dimensity 9400, 50MP Hasselblad camera, and 80W charging.',
    specs: [{ label: 'Display', value: '6.59" LTPO AMOLED 2760x1256 120Hz' }, { label: 'Chip', value: 'Dimensity 9400' }, { label: 'Camera', value: '50+50+50 MP Hasselblad' }, { label: 'Battery', value: '5630 mAh 80W' }] },
  { id: 21, brand: 'honor', name: 'Honor 200', price: 259000, storage: '256GB', img: 'https://fdn2.gsmarena.com/vv/bigpic/honor-200-.jpg',
    desc: 'Stylish mid-ranger with 50MP main camera, 120Hz AMOLED, and slim design.',
    specs: [{ label: 'Display', value: '6.7" AMOLED 2664x1200 120Hz' }, { label: 'Chip', value: 'Snapdragon 7 Gen 3' }, { label: 'Camera', value: '50+12+2 MP' }, { label: 'Battery', value: '5200 mAh 100W' }] },
  { id: 22, brand: 'realme', name: 'Realme GT 7', price: 279000, storage: '256GB', img: 'https://fdn2.gsmarena.com/vv/bigpic/realme-gt-7.jpg',
    desc: 'Performance beast with Snapdragon 8s Gen 3, 50MP Sony camera, and 120W GT charging.',
    specs: [{ label: 'Display', value: '6.78" AMOLED 2780x1264 144Hz' }, { label: 'Chip', value: 'Snapdragon 8s Gen 3' }, { label: 'Camera', value: '50+8 MP' }, { label: 'Battery', value: '5500 mAh 120W' }] },
  { id: 23, brand: 'apple', name: 'iPhone 16e', price: 429000, storage: '128GB', img: 'https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-16e.jpg',
    desc: 'The affordable iPhone 16 series member with A18 chip and Apple Intelligence.',
    specs: [{ label: 'Display', value: '6.1" OLED 2532x1170' }, { label: 'Chip', value: 'A18' }, { label: 'Camera', value: '48 MP' }, { label: 'Battery', value: '3561 mAh' }] },
  { id: 24, brand: 'apple', name: 'iPhone 15', price: 449000, storage: '128GB', img: 'https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-15.jpg',
    desc: 'Dynamic Island, 48MP camera, and A16 Bionic chip in a sleek design.',
    specs: [{ label: 'Display', value: '6.1" OLED 2556x1179' }, { label: 'Chip', value: 'A16 Bionic' }, { label: 'Camera', value: '48+12 MP' }, { label: 'Battery', value: '3349 mAh' }] },
  { id: 25, brand: 'apple', name: 'iPhone 14', price: 389000, storage: '128GB', img: 'https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-14.jpg',
    desc: 'A15 Bionic, 12MP dual camera, and emergency SOS via satellite.',
    specs: [{ label: 'Display', value: '6.1" OLED 2532x1170' }, { label: 'Chip', value: 'A15 Bionic' }, { label: 'Camera', value: '12+12 MP' }, { label: 'Battery', value: '3279 mAh' }] },
  { id: 26, brand: 'apple', name: 'iPhone 14 Plus', price: 419000, storage: '128GB', img: 'https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-14-plus.jpg',
    desc: 'Big-screen iPhone with 6.7" OLED and excellent battery life.',
    specs: [{ label: 'Display', value: '6.7" OLED 2778x1284' }, { label: 'Chip', value: 'A15 Bionic' }, { label: 'Camera', value: '12+12 MP' }, { label: 'Battery', value: '4323 mAh' }] },
  { id: 27, brand: 'apple', name: 'iPhone 14 Pro', price: 479000, storage: '256GB', img: 'https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-14-pro.jpg',
    desc: 'Dynamic Island, A16 Bionic, 48MP pro camera system.',
    specs: [{ label: 'Display', value: '6.1" OLED 2556x1179 120Hz' }, { label: 'Chip', value: 'A16 Bionic' }, { label: 'Camera', value: '48+12+12 MP' }, { label: 'Battery', value: '3200 mAh' }] },
  { id: 28, brand: 'samsung', name: 'Samsung Galaxy Z Flip6', price: 459000, storage: '512GB', img: 'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-z-flip6.jpg',
    desc: 'Foldable flip phone with 50MP camera, large cover screen, and Snapdragon 8 Gen 3.',
    specs: [{ label: 'Display', value: '6.7" Foldable AMOLED 2640x1080 120Hz' }, { label: 'Chip', value: 'Snapdragon 8 Gen 3' }, { label: 'Camera', value: '50+12 MP' }, { label: 'Battery', value: '4000 mAh' }] },
  { id: 29, brand: 'samsung', name: 'Samsung Galaxy A15 5G', price: 139000, storage: '128GB', img: 'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a15-5g.jpg',
    desc: 'Affordable 5G phone with Super AMOLED 90Hz display and 50MP camera.',
    specs: [{ label: 'Display', value: '6.5" Super AMOLED 2340x1080 90Hz' }, { label: 'Chip', value: 'Dimensity 6100+' }, { label: 'Camera', value: '50+5+2 MP' }, { label: 'Battery', value: '5000 mAh' }] },
  { id: 30, brand: 'samsung', name: 'Samsung Galaxy A16 5G', price: 159000, storage: '128GB', img: 'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a16-5g.jpg',
    desc: 'Latest Galaxy A series with 6.7" Super AMOLED and 50MP OIS camera.',
    specs: [{ label: 'Display', value: '6.7" Super AMOLED 2340x1080 90Hz' }, { label: 'Chip', value: 'Dimensity 6300' }, { label: 'Camera', value: '50+5+2 MP' }, { label: 'Battery', value: '5000 mAh' }] },
  { id: 31, brand: 'samsung', name: 'Samsung Galaxy A26', price: 189000, storage: '128GB', img: 'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a26.jpg',
    desc: 'Mid-range Galaxy with Super AMOLED 120Hz and 50MP camera with OIS.',
    specs: [{ label: 'Display', value: '6.64" Super AMOLED 2340x1080 120Hz' }, { label: 'Chip', value: 'Exynos 1380' }, { label: 'Camera', value: '50+8+2 MP' }, { label: 'Battery', value: '5000 mAh' }] },
  { id: 32, brand: 'samsung', name: 'Samsung Galaxy M55', price: 219000, storage: '128GB', img: 'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-m55.jpg',
    desc: 'Galaxy M series with 6.7" Super AMOLED 120Hz and massive 6000 mAh battery.',
    specs: [{ label: 'Display', value: '6.7" Super AMOLED 2400x1080 120Hz' }, { label: 'Chip', value: 'Snapdragon 7 Gen 1' }, { label: 'Camera', value: '50+8+2 MP' }, { label: 'Battery', value: '6000 mAh' }] },
  { id: 33, brand: 'samsung', name: 'Samsung Galaxy S23 FE', price: 299000, storage: '256GB', img: 'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s23-fe.jpg',
    desc: 'Fan Edition flagship with 50MP camera, 120Hz display, and flagship chipset.',
    specs: [{ label: 'Display', value: '6.4" Dynamic AMOLED 2340x1080 120Hz' }, { label: 'Chip', value: 'Exynos 2200' }, { label: 'Camera', value: '50+8+12 MP' }, { label: 'Battery', value: '4500 mAh' }] },
  { id: 34, brand: 'xiaomi', name: 'Xiaomi 13T Pro', price: 299000, storage: '256GB', img: 'https://fdn2.gsmarena.com/vv/bigpic/xiaomi-13t-pro.jpg',
    desc: 'Leica co-engineered camera system with Dimensity 9200+ and 120W charging.',
    specs: [{ label: 'Display', value: '6.67" AMOLED 2712x1220 144Hz' }, { label: 'Chip', value: 'Dimensity 9200+' }, { label: 'Camera', value: '50+50+12 MP Leica' }, { label: 'Battery', value: '5000 mAh 120W' }] },
  { id: 35, brand: 'xiaomi', name: 'Xiaomi Redmi Note 12 Pro', price: 169000, storage: '256GB', img: 'https://fdn2.gsmarena.com/vv/bigpic/xiaomi-redmi-note-12-pro.jpg',
    desc: 'Popular mid-ranger with 50MP OIS camera, 67W charging, and 120Hz AMOLED.',
    specs: [{ label: 'Display', value: '6.67" AMOLED 2400x1080 120Hz' }, { label: 'Chip', value: 'Dimensity 1080' }, { label: 'Camera', value: '50+8+2 MP' }, { label: 'Battery', value: '5000 mAh 67W' }] },
  { id: 36, brand: 'xiaomi', name: 'POCO X6 Pro', price: 199000, storage: '256GB', img: 'https://fdn2.gsmarena.com/vv/bigpic/xiaomi-poco-x6-pro.jpg',
    desc: 'Performance-focused phone with Dimensity 8300 Ultra and 120W HyperCharge.',
    specs: [{ label: 'Display', value: '6.67" AMOLED 2712x1220 120Hz' }, { label: 'Chip', value: 'Dimensity 8300 Ultra' }, { label: 'Camera', value: '64+8+2 MP' }, { label: 'Battery', value: '5000 mAh 120W' }] },
  { id: 37, brand: 'google', name: 'Google Pixel 8 Pro', price: 459000, storage: '256GB', img: 'https://fdn2.gsmarena.com/vv/bigpic/google-pixel-8-pro.jpg',
    desc: 'Google flagship with Tensor G3, 50MP main camera, and 7 years of updates.',
    specs: [{ label: 'Display', value: '6.7" LTPO OLED 2992x1344 120Hz' }, { label: 'Chip', value: 'Tensor G3' }, { label: 'Camera', value: '50+48+48 MP' }, { label: 'Battery', value: '5050 mAh' }] },
  { id: 38, brand: 'google', name: 'Google Pixel 8', price: 389000, storage: '128GB', img: 'https://fdn2.gsmarena.com/vv/bigpic/google-pixel-8.jpg',
    desc: 'Compact Pixel with Tensor G3, 50MP camera, and Google AI features.',
    specs: [{ label: 'Display', value: '6.2" OLED 2400x1080 120Hz' }, { label: 'Chip', value: 'Tensor G3' }, { label: 'Camera', value: '50+12 MP' }, { label: 'Battery', value: '4575 mAh' }] },
  { id: 39, brand: 'oneplus', name: 'OnePlus 12R', price: 299000, storage: '256GB', img: 'https://fdn2.gsmarena.com/vv/bigpic/oneplus-12r.jpg',
    desc: 'Flagship killer with Snapdragon 8 Gen 2, 50MP Sony camera, and 100W charging.',
    specs: [{ label: 'Display', value: '6.78" LTPO AMOLED 2780x1264 120Hz' }, { label: 'Chip', value: 'Snapdragon 8 Gen 2' }, { label: 'Camera', value: '50+8+2 MP' }, { label: 'Battery', value: '5500 mAh 100W' }] },
  { id: 40, brand: 'nothing', name: 'Nothing Phone (2a)', price: 219000, storage: '256GB', img: 'https://fdn2.gsmarena.com/vv/bigpic/nothing-phone-2a.jpg',
    desc: 'Stylish mid-ranger with transparent design, Glyph lights, and Dimensity 7200 Pro.',
    specs: [{ label: 'Display', value: '6.7" AMOLED 2412x1084 120Hz' }, { label: 'Chip', value: 'Dimensity 7200 Pro' }, { label: 'Camera', value: '50+50 MP' }, { label: 'Battery', value: '5000 mAh 45W' }] },
  { id: 41, brand: 'realme', name: 'Realme 12 Pro+', price: 239000, storage: '256GB', img: 'https://fdn2.gsmarena.com/vv/bigpic/realme-12-pro-plus.jpg',
    desc: 'Mid-range camera phone with 64MP periscope zoom and 120Hz AMOLED.',
    specs: [{ label: 'Display', value: '6.7" AMOLED 2412x1080 120Hz' }, { label: 'Chip', value: 'Snapdragon 7s Gen 2' }, { label: 'Camera', value: '50+64+8 MP' }, { label: 'Battery', value: '5000 mAh 67W' }] },
  { id: 42, brand: 'honor', name: 'Honor Magic6 Pro', price: 419000, storage: '512GB', img: 'https://fdn2.gsmarena.com/vv/bigpic/honor-magic6-pro.jpg',
    desc: 'Premium flagship with Snapdragon 8 Gen 3, 180MP periscope zoom, and 80W charging.',
    specs: [{ label: 'Display', value: '6.8" LTPO OLED 2800x1280 120Hz' }, { label: 'Chip', value: 'Snapdragon 8 Gen 3' }, { label: 'Camera', value: '50+180+50 MP' }, { label: 'Battery', value: '5600 mAh 80W' }] },
  { id: 43, brand: 'apple', name: 'iPhone 13 Pro', price: 349000, storage: '256GB', img: 'https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-13-pro.jpg',
    desc: 'ProMotion 120Hz display, A15 Bionic, and pro triple-camera system.',
    specs: [{ label: 'Display', value: '6.1" OLED 2532x1170 120Hz' }, { label: 'Chip', value: 'A15 Bionic' }, { label: 'Camera', value: '12+12+12 MP' }, { label: 'Battery', value: '3095 mAh' }] },
  { id: 44, brand: 'apple', name: 'iPhone 13 Pro Max', price: 389000, storage: '256GB', img: 'https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-13-pro-max.jpg',
    desc: 'The biggest iPhone with ProMotion, A15 Bionic, and best battery life.',
    specs: [{ label: 'Display', value: '6.7" OLED 2778x1284 120Hz' }, { label: 'Chip', value: 'A15 Bionic' }, { label: 'Camera', value: '12+12+12 MP' }, { label: 'Battery', value: '4352 mAh' }] },
  { id: 45, brand: 'apple', name: 'iPhone 12', price: 299000, storage: '128GB', img: 'https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-12.jpg',
    desc: 'First iPhone with OLED, MagSafe, and 5G support.',
    specs: [{ label: 'Display', value: '6.1" OLED 2532x1170' }, { label: 'Chip', value: 'A14 Bionic' }, { label: 'Camera', value: '12+12 MP' }, { label: 'Battery', value: '2815 mAh' }] },
  { id: 46, brand: 'samsung', name: 'Samsung Galaxy A14 5G', price: 129000, storage: '64GB', img: 'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a14-5g.jpg',
    desc: 'Budget 5G phone with 6.6" PLS LCD, 50MP camera, and 5000 mAh battery.',
    specs: [{ label: 'Display', value: '6.6" PLS LCD 2408x1080 90Hz' }, { label: 'Chip', value: 'Dimensity 700' }, { label: 'Camera', value: '50+2+2 MP' }, { label: 'Battery', value: '5000 mAh' }] },
  { id: 47, brand: 'xiaomi', name: 'Redmi Note 13 4G', price: 149000, storage: '128GB', img: 'https://fdn2.gsmarena.com/vv/bigpic/xiaomi-redmi-note-13-4g.jpg',
    desc: 'Best-selling budget phone with 108MP camera and 120Hz AMOLED.',
    specs: [{ label: 'Display', value: '6.67" AMOLED 2400x1080 120Hz' }, { label: 'Chip', value: 'Snapdragon 685' }, { label: 'Camera', value: '108+8+2 MP' }, { label: 'Battery', value: '5000 mAh 33W' }] },
  { id: 48, brand: 'xiaomi', name: 'POCO X5 Pro 5G', price: 189000, storage: '256GB', img: 'https://fdn2.gsmarena.com/vv/bigpic/xiaomi-poco-x5-pro-5g.jpg',
    desc: 'Mid-range powerhouse with Snapdragon 778G, 108MP camera, and 67W charging.',
    specs: [{ label: 'Display', value: '6.67" AMOLED 2400x1080 120Hz' }, { label: 'Chip', value: 'Snapdragon 778G' }, { label: 'Camera', value: '108+8+2 MP' }, { label: 'Battery', value: '5000 mAh 67W' }] },
  { id: 49, brand: 'oneplus', name: 'OnePlus 11', price: 349000, storage: '256GB', img: 'https://fdn2.gsmarena.com/vv/bigpic/oneplus-11.jpg',
    desc: 'Flagship with Snapdragon 8 Gen 2, Hasselblad camera, and 100W charging.',
    specs: [{ label: 'Display', value: '6.7" LTPO AMOLED 3216x1440 120Hz' }, { label: 'Chip', value: 'Snapdragon 8 Gen 2' }, { label: 'Camera', value: '50+48+32 MP Hasselblad' }, { label: 'Battery', value: '5000 mAh 100W' }] },
  { id: 50, brand: 'google', name: 'Google Pixel 7a', price: 269000, storage: '128GB', img: 'https://fdn2.gsmarena.com/vv/bigpic/google-pixel-7a.jpg',
    desc: 'Mid-range Pixel with Tensor G2, 64MP camera, and Pixel-exclusive features.',
    specs: [{ label: 'Display', value: '6.1" OLED 2400x1080 90Hz' }, { label: 'Chip', value: 'Tensor G2' }, { label: 'Camera', value: '64+13 MP' }, { label: 'Battery', value: '4385 mAh' }] },
  { id: 51, brand: 'honor', name: 'Honor 90', price: 219000, storage: '256GB', img: 'https://fdn2.gsmarena.com/vv/bigpic/honor-90.jpg',
    desc: 'Stylish mid-ranger with 200MP camera, 120Hz AMOLED, and slim curved design.',
    specs: [{ label: 'Display', value: '6.7" AMOLED 2664x1200 120Hz' }, { label: 'Chip', value: 'Snapdragon 7 Gen 1' }, { label: 'Camera', value: '200+12+2 MP' }, { label: 'Battery', value: '5000 mAh 66W' }] },
  { id: 52, brand: 'nothing', name: 'Nothing Phone (1)', price: 249000, storage: '256GB', img: 'https://fdn2.gsmarena.com/vv/bigpic/nothing-phone-1.jpg',
    desc: 'First Nothing phone with transparent design, Glyph lights, and Snapdragon 778G+.',
    specs: [{ label: 'Display', value: '6.55" OLED 2400x1080 120Hz' }, { label: 'Chip', value: 'Snapdragon 778G+' }, { label: 'Camera', value: '50+50 MP' }, { label: 'Battery', value: '4500 mAh 33W' }] },
];
